name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:15.8.0
    ports:
    - '5432:5432' # vai passar a porta 5432 do container(postgressql) para a porta 5432 da minha maquina 
    environment: # variaveis de ambientes / credenciais do bd
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=inorbit
